### ISSUE TITLE
SillyNameMaker.zip isn't actually a zip file.

### ISSUE THREAD

**Issue by ericsnowcurrently** [actions-on-google/apiai-silly-name-maker#1]
I went to look at the zipped files and found that SillyNameMaker.zip is actually an HTML file.  Have I missed something or is SillyNameMaker.zip the wrong file?

**Comment by entertailion** [comment]
SillyNameMaker.zip is definitely a zip file. The best is to do a git clone to ensure you download all the files in the correct format.
